language: python

sudo: false

addons:
  apt:
    packages:
    - libopenobex1-dev

before_install:
    - pip install codecov
    - pip install coveralls
    
install:
    - pip install pybluez
    - pip install --allow-all-external --allow-unverified lightblue lightblue

script: 
    - nosetests
    - coverage run --source=pbap setup.py test
    
after_success:
    - coveralls
    - codecov

notification:
    email:
        - eliasj@student.chalmers.se

  
